version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./weights:/app/weights  # Монтируем каталог с весами моделей
      - ./data_folder:/app/data_folder  # Монтируем каталог с данными
    environment:
      - MODEL_PATH=/app/weights
